@startuml
'https://plantuml.com/sequence-diagram

class WordFrequencyFinder{
    -words: HashTag<String, Integer>
    +getWords(): HashTag<String, Integer>
    +readFile()
    +printFrequency()
}

@enduml