@startuml
'https://plantuml.com/class-diagram

class NameSorter {
    +names : ArrayList<String>
    +readFile() : ArrayList<String>
    +sortNames(ArrayList<String>) : ArrayList<String>
    +printNames(ArrayList<String>)
}


@enduml