@startuml
'https://plantuml.com/sequence-diagram

class ProductSearch{
    -input: Scanner
    -products: JsonArray
    +readFile()
    +getUserInput(): String
    +searchProduct()
    +isInside():boolean
    +getProducts(): JsonArray
}
@enduml